### ISSUE TITLE
This exists!

### ISSUE THREAD

**Issue by zeke** [octokit/fixtures-server#1]
😎

**Comment by gr2m** [comment]
![](https://media.giphy.com/media/gngO1gmBhS9na/giphy.gif)

**Comment by gr2m** [comment]
wanna turn this into an electron app?

**Comment by zeke** [comment]
Why Electron? So it can have a GUI or something?

**Comment by gr2m** [comment]
yeah ... I was thinking about what a GUI could look like for this. It could provide better debugging if a test would fail ... yeah dunno yet
